[package]
name = "day24"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
good_lp = "1.7.0"
z3 = {version="0.11.2", features = ["static-link-z3"]}
